//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaTaxis
{
    using System;
    using System.Collections.Generic;
    
    public partial class conductores
    {
        public long id { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public long placa_id { get; set; }
    
        public virtual taxis taxis { get; set; }
    }
}
