//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaTaxis
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taxis()
        {
            this.conductores = new HashSet<conductores>();
        }
    
        public long id { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Telefono { get; set; }
        public long propietarios_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conductores> conductores { get; set; }
        public virtual propietarios propietarios { get; set; }
    }
}
